Update dioxus dependency to 0.5
DioxusLabs/markdown pull request #6
Opened 2024-04-04 08:53 UTC by Stygmates

Updates the crate to support dioxus 0.5.
The example runs locally with the updated dependency so it should be good.

2024-04-04 09:30 UTC, marc2332 requested changes

2024-04-04 09:30 UTC, marc2332 commented on Cargo.toml
```toml
[dependencies]
dioxus = { version = "0.5" }
pulldown-cmark = "0.9.3"

[dev-dependencies]
dioxus = { version = "0.5", features = ["desktop"] }
```

2024-04-04 09:30 UTC, marc2332 commented on src/lib.rs
> +    content: Signal<String>,
I would use ReadOnlySignal instead.

2024-04-04 09:30 UTC, marc2332 commented on examples/bulma.rs
> +    let content = use_signal(|| String::from(include_str!("../README.md")));
No need to wrap `include_str!("../README.md")` in a signal we you change the ReadOnlySignal thing

2024-04-04 09:30 UTC, marc2332 commented on examples/bulma.rs
> +    dioxus::launch(app);
```suggestion
    launch(app);
```

2024-04-04 12:49 UTC, Stygmates commented
Thank you for your review! I think I applied all of your suggestions, let me know if I need to change anything else.

2024-04-04 16:46 UTC, merged

2024-04-04 16:46 UTC, jkelleyrtp commented
Looks good, thanks!

2024-04-07 11:02 UTC, ifsheldon commented
Hey! I think you brought a silent breaking change here.  @Stygmates 
https://github.com/DioxusLabs/markdown/blame/5ca15aa634de28b9241c2e0acc863231f5618107/Cargo.toml#L9
My web code no longer complies due to the `desktop` feature here. It took me a while to find out the mystery `tokio` dependency that showed up

2024-04-07 11:05 UTC, marc2332 commented
> Hey! I think you brought a silent breaking change here. @Stygmates https://github.com/DioxusLabs/markdown/blame/5ca15aa634de28b9241c2e0acc863231f5618107/Cargo.toml#L9 My web code no longer complies due to the `desktop` feature here. It took me a while to find out the mystery `tokio` dependency that showed up

Seems like my [comment](https://github.com/DioxusLabs/markdown/pull/6#discussion_r1551320617) was not applied

2024-04-07 11:12 UTC, marc2332 commented
> Hey! I think you brought a silent breaking change here. @Stygmates https://github.com/DioxusLabs/markdown/blame/5ca15aa634de28b9241c2e0acc863231f5618107/Cargo.toml#L9 My web code no longer complies due to the `desktop` feature here. It took me a while to find out the mystery `tokio` dependency that showed up

Opened https://github.com/DioxusLabs/markdown/pull/7